# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Linaro LKFT
#email: lkft-triage@lists.linaro.org # have to figure out what lists to publish
irc_channel: linaro-lkft
github_username: danrue
github_repository: danrue/lkft-site
github_repository_url: https://github.com/danrue/lkft-site
description: >- # this means to ignore newlines until "baseurl:"
  Linaro's Linux Kernel Functional Testing (LKFT) project validates Linux
  stable kernels on arm, arm64, and x86_64 consumer hardware.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lkft.linaro.org" # the base hostname & protocol for your site, e.g. http://example.com
header_pages:
  - about/index.md
  - faq/index.md
  - boards/index.md
  - branches/index.md
  - tests/index.md
  - changelog/index.md

# Jekyll Assets setup
assets:
  # Compress JS Assets - uses the uglifier plugin 
  compress:
        js: true
  # Autoprefixer default settings
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  # These are the paths to look for assets
  sources:
    - assets/images/
    - assets/css/
    - assets/js/
    
# Sass Configuration for the site styles
sass:
    style: compressed
    load_paths:
        - assets/css
    
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy: 
    # Toggle compression of HTML
    compress_html: true
    # JS Path added to exclude to stop errors.
    exclude: ["assets/**/*.js"]   
      
# Build settings
markdown: kramdown

theme: jumbo-jekyll-theme

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - bootstrap-sass
    - uglifier
    - jekyll-assets
    - jekyll-theme-assets
    - jekyll-tidy
    - jekyll-data
    - jekyll-redirect-from
    - autoprefixer-rails
    - jekyll-paginate-v2
